set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

if (PORT MATCHES "steamworks-sdk")
	set(VCPKG_ENV_PASSTHROUGH STEAMWORKS_SDK)
	set(MAJOR 1)
	set(MINOR 34)
endif()