set(SOURCE_FILES
	${ROOT_DIR}/src/c++/Events/Events.h
	${ROOT_DIR}/src/c++/Events/Handlers/CurrentRadiationSource.h
	${ROOT_DIR}/src/c++/Events/Handlers/ItemCrafted.h
	${ROOT_DIR}/src/c++/Events/Handlers/PipboyLightEvent.h
	${ROOT_DIR}/src/c++/Events/Handlers/TESContainerChanged.h
	${ROOT_DIR}/src/c++/Forms/Forms.h
	${ROOT_DIR}/src/c++/Misc/Fixes.h
	${ROOT_DIR}/src/c++/Misc/Fixes/OnStoryCraftItem.h
	${ROOT_DIR}/src/c++/Misc/Patches.h
	${ROOT_DIR}/src/c++/Misc/Patches/LoadEditorIDs.h
	${ROOT_DIR}/src/c++/PCH.cpp
	${ROOT_DIR}/src/c++/PCH.h
	${ROOT_DIR}/src/c++/Scripts/ObScript.h
	${ROOT_DIR}/src/c++/Scripts/ObScript/BetaComment.h
	${ROOT_DIR}/src/c++/Scripts/ObScript/FreePlayer.h
	${ROOT_DIR}/src/c++/Scripts/ObScript/GetBaseObject.h
	${ROOT_DIR}/src/c++/Scripts/ObScript/GetDefaultObject.h
	${ROOT_DIR}/src/c++/Scripts/ObScript/QuitGame.h
	${ROOT_DIR}/src/c++/Scripts/ObScript/SpellHasCastingPerk.h
	${ROOT_DIR}/src/c++/Scripts/Papyrus.h
	${ROOT_DIR}/src/c++/Scripts/Papyrus/BakaUtil.h
	${ROOT_DIR}/src/c++/Scripts/Papyrus/ScriptObject.h
	${ROOT_DIR}/src/c++/Scripts/Papyrus/Shared/FunctionArgs.h
	${ROOT_DIR}/src/c++/Scripts/Papyrus/Shared/RegistrationMap.cpp
	${ROOT_DIR}/src/c++/Scripts/Papyrus/Shared/RegistrationMap.h
	${ROOT_DIR}/src/c++/Scripts/Papyrus/StringUtil.h
	${ROOT_DIR}/src/c++/Serialization/Serialization.h
	${ROOT_DIR}/src/c++/Settings.h
	${ROOT_DIR}/src/c++/SteamAPI/SteamAPI.cpp
	${ROOT_DIR}/src/c++/SteamAPI/SteamAPI.h
	${ROOT_DIR}/src/c++/Workshop/Workshop.h
	${ROOT_DIR}/src/c++/main.cpp
)
